### PR TITLE
load Xenium clustering into h5ad file

### PR DESCRIPTION
**Pull request by BioinfoTongLI**

### CODE REVIEW

**Comment by BioinfoTongLI** [comment]
looks like an doc action deployment issue?

**Review by davehorsfall — COMMENTED** [review]
I'm not familiar enough with this Xenium code to approve. Is this a blocker for submission @BioinfoTongLI? Does the cluster need to be reindexed like this? @dannda can you review please?

**Comment by BioinfoTongLI** [comment]
not really. Especially you said that the 10x Xenium dataset is working well with the current version. We can come back to this after biorXiv submission

**Comment by dannda** [comment]
Current version was not loading embeddings and clusters so we do need to merge this.
I've dded logic similar to processing spaceranger to load all clusters and embeddings.

**Pull request merged**
